[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "aiohttp>=3.11.13",
    "python-telegram-bot==20.5",
    "telegram>=0.0.1",
    "twilio>=9.5.0",
]
